

const SCHEMES = [
  {
    id: 12,
    title: "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
    emoji: "🏦",
    region: "Central",
    desc: "Ensures access to financial services like savings accounts, credit, insurance, and pension.",
    fund: "Zero balance account + accidental & life insurance",
    tags: ["Banking", "Financial Inclusion"],
  },
  {
    id: 13,
    title: "Sukanya Samriddhi Yojana (SSY)",
    emoji: "👧",
    region: "Central",
    desc: "Savings scheme for the girl child’s education and marriage with high interest rate benefits.",
    fund: "Up to ₹1.5 lakh yearly deposit with tax benefits",
    tags: ["Girl Child", "Savings"],
  },
  {
    id: 14,
    title: "Pradhan Mantri MUDRA Yojana (PMMY)",
    emoji: "💰",
    region: "Central",
    desc: "Provides collateral-free loans to small and micro businesses under Shishu, Kishor, and Tarun categories.",
    fund: "₹50,000 – ₹10 lakh loans",
    tags: ["Entrepreneurship", "MSME"],
  },
  {
    id: 15,
    title: "Stand-Up India Scheme",
    emoji: "🚀",
    region: "Central",
    desc: "Supports SC/ST and women entrepreneurs with bank loans to start greenfield enterprises.",
    fund: "₹10 lakh – ₹1 crore loan support",
    tags: ["Women", "Entrepreneurship"],
  },
  {
    id: 16,
    title: "Kisan Credit Card (KCC)",
    emoji: "🌾",
    region: "Central",
    desc: "Provides timely credit to farmers for cultivation and other needs with flexible repayment.",
    fund: "Crop loan up to ₹3 lakh at concessional interest",
    tags: ["Farmers", "Agriculture"],
  },
  {
    id: 17,
    title: "PM Kisan Samman Nidhi (PM-KISAN)",
    emoji: "👨‍🌾",
    region: "Central",
    desc: "Provides income support to small and marginal farmers directly into their bank accounts.",
    fund: "₹6,000 per year in 3 installments",
    tags: ["Farmers", "Direct Benefit Transfer"],
  },
  {
    id: 18,
    title: "Beti Bachao Beti Padhao (BBBP)",
    emoji: "🌸",
    region: "Central",
    desc: "Campaign to prevent gender-biased sex selection and promote education for girl children.",
    fund: "Awareness + Education incentives",
    tags: ["Women", "Girl Child", "Education"],
  },
  {
    id: 19,
    title: "PM Ujjwala Yojana",
    emoji: "🪔",
    region: "Central",
    desc: "Provides free LPG connections to women from BPL households to promote clean cooking.",
    fund: "Free LPG connection + subsidy",
    tags: ["Women", "Health", "Energy"],
  },
  {
    id: 20,
    title: "National Food Security Act (NFSA)",
    emoji: "🥖",
    region: "Central",
    desc: "Ensures subsidized food grains to eligible households through the Public Distribution System.",
    fund: "₹1–₹3 per kg rice/wheat",
    tags: ["Food", "BPL"],
  },
  {
    id: 21,
    title: "Chief Minister’s Marriage Assistance Scheme",
    emoji: "💍",
    region: "State",
    desc: "Financial assistance for marriage of girls from poor families in several states.",
    fund: "₹25,000 – ₹50,000 + gold support (varies by state)",
    tags: ["Women", "Marriage Assistance"],
  },
  // … previous ones (id: 1 – 21)

  {
    id: 22,
    title: "Atal Pension Yojana (APY)",
    emoji: "💳",
    region: "Central",
    desc: "Social security scheme providing pension to unorganized sector workers after 60 years.",
    fund: "₹1,000 – ₹5,000 per month pension (based on contribution)",
    tags: ["Pension", "Unorganized Sector"],
  },
  {
    id: 23,
    title: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
    emoji: "🛡️",
    region: "Central",
    desc: "Accidental death and disability insurance scheme with very low premium.",
    fund: "₹2 lakh accidental cover at ₹12/year",
    tags: ["Insurance", "Low-Income"],
  },
  {
    id: 24,
    title: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
    emoji: "⚰️",
    region: "Central",
    desc: "Life insurance cover available to all savings bank account holders.",
    fund: "₹2 lakh life cover at ₹330/year",
    tags: ["Insurance", "Life"],
  },
  {
    id: 25,
    title: "National Social Assistance Programme (NSAP)",
    emoji: "🤝",
    region: "Central",
    desc: "Provides pensions to elderly, widows, and disabled persons from BPL households.",
    fund: "₹200 – ₹500 per month",
    tags: ["Pension", "Social Security"],
  },
  {
    id: 26,
    title: "Mid-Day Meal Scheme",
    emoji: "🍛",
    region: "Central",
    desc: "Provides free lunch to school children to improve nutrition and attendance.",
    fund: "Free cooked meals at schools",
    tags: ["Nutrition", "Education", "Children"],
  },
  {
    id: 27,
    title: "Integrated Child Development Services (ICDS)",
    emoji: "🍼",
    region: "Central",
    desc: "Delivers health, nutrition, and preschool education services to children under 6 and mothers.",
    fund: "Free food + health check-ups + education",
    tags: ["Children", "Women", "Health"],
  },
  {
    id: 28,
    title: "National Health Mission (NHM)",
    emoji: "🏥",
    region: "Central",
    desc: "Strengthens public health systems with focus on rural healthcare and maternal-child health.",
    fund: "Free/subsidized healthcare services",
    tags: ["Health", "Rural Development"],
  },
  {
    id: 29,
    title: "Swachh Bharat Mission (SBM)",
    emoji: "🚽",
    region: "Central",
    desc: "Aims to eliminate open defecation and improve sanitation facilities across India.",
    fund: "₹12,000 per household toilet + community support",
    tags: ["Sanitation", "Health", "Rural"],
  },
  {
    id: 30,
    title: "National Rural Health Mission – Janani Suraksha Yojana",
    emoji: "🤰",
    region: "Central",
    desc: "Cash incentive scheme to promote institutional delivery among pregnant women.",
    fund: "₹700 – ₹1,400 cash assistance (varies by state)",
    tags: ["Women", "Maternity", "Health"],
  },
  {
    id: 31,
    title: "National Handloom Development Programme",
    emoji: "🧶",
    region: "Central",
    desc: "Supports handloom weavers with training, marketing, and financial assistance.",
    fund: "Credit support + subsidy",
    tags: ["Artisans", "Livelihood"],
  },
  {
    id: 32,
    title: "Rashtriya Krishi Vikas Yojana (RKVY)",
    emoji: "🌱",
    region: "Central",
    desc: "Supports states in agriculture development through project-based funding.",
    fund: "Grant-based financial assistance",
    tags: ["Agriculture", "Farmers"],
  },
  {
    id: 33,
    title: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    emoji: "🌾",
    region: "Central",
    desc: "Crop insurance scheme protecting farmers against crop loss due to natural calamities.",
    fund: "Crop loss insurance cover",
    tags: ["Farmers", "Insurance"],
  },
  {
    id: 34,
    title: "Skill India Mission",
    emoji: "🎓",
    region: "Central",
    desc: "Large-scale initiative to train youth in employable skills across various sectors.",
    fund: "Free skill training + certification",
    tags: ["Skills", "Youth", "Employment"],
  },
  {
    id: 35,
    title: "Startup India",
    emoji: "💡",
    region: "Central",
    desc: "Promotes entrepreneurship with tax exemptions, funding support, and easier compliance.",
    fund: "Tax benefits + funding + incubation",
    tags: ["Entrepreneurship", "Innovation"],
  },
  {
    id: 36,
    title: "Digital India Programme",
    emoji: "💻",
    region: "Central",
    desc: "Transforms India into a digitally empowered society and knowledge economy.",
    fund: "Subsidized digital services + infrastructure support",
    tags: ["Technology", "Governance"],
  },
  {
    id: 37,
    title: "National AYUSH Mission",
    emoji: "🌿",
    region: "Central",
    desc: "Promotes traditional systems of medicine like Ayurveda, Yoga, Unani, Siddha, and Homeopathy.",
    fund: "Support for AYUSH hospitals, dispensaries, and education",
    tags: ["Health", "AYUSH"],
  },
  {
    id: 38,
    title: "Mission Indradhanush",
    emoji: "💉",
    region: "Central",
    desc: "Universal immunization program to cover children and pregnant women.",
    fund: "Free vaccines + healthcare support",
    tags: ["Health", "Children", "Women"],
  },
  {
    id: 39,
    title: "Rashtriya Madhyamik Shiksha Abhiyan (RMSA)",
    emoji: "🏫",
    region: "Central",
    desc: "Improves access to secondary education and enhances quality of schooling.",
    fund: "Funding for schools, infrastructure, and training",
    tags: ["Education", "Youth"],
  },
  {
    id: 40,
    title: "National Means-cum-Merit Scholarship Scheme (NMMSS)",
    emoji: "🎓",
    region: "Central",
    desc: "Scholarships for economically weaker students to reduce dropouts at secondary level.",
    fund: "₹12,000 per year per student",
    tags: ["Scholarship", "Students"],
  },
  {
    id: 41,
    title: "National Skill Development Mission",
    emoji: "🧑‍🏫",
    region: "Central",
    desc: "Umbrella mission to train people across sectors for employability and productivity.",
    fund: "Skill training + placement assistance",
    tags: ["Skills", "Employment"],
  },
  {
    id: 42,
    title: "National Rural Employment Guarantee Act (MGNREGA)",
    emoji: "🛠️",
    region: "Central",
    desc: "Guarantees 100 days of wage employment to every rural household.",
    fund: "Wage payment per day of unskilled work",
    tags: ["Employment", "Rural Development"],
  },
  {
    id: 43,
    title: "Sarva Shiksha Abhiyan (SSA)",
    emoji: "📖",
    region: "Central",
    desc: "Flagship program for universalization of elementary education for children 6–14 years.",
    fund: "Free books, uniforms, and teacher support",
    tags: ["Education", "Children"],
  },
  {
    id: 44,
    title: "National Bamboo Mission",
    emoji: "🎍",
    region: "Central",
    desc: "Promotes growth of bamboo sector for livelihood and ecological benefits.",
    fund: "Subsidy for bamboo cultivation + marketing",
    tags: ["Agriculture", "Environment"],
  },
  {
    id: 45,
    title: "PM eVIDYA",
    emoji: "📺",
    region: "Central",
    desc: "Digital learning initiative ensuring education through TV, radio, and online platforms.",
    fund: "Free digital classes + e-resources",
    tags: ["Education", "Digital"],
  },
  {
    id: 46,
    title: "One Nation One Ration Card (ONORC)",
    emoji: "🥗",
    region: "Central",
    desc: "Allows beneficiaries to access subsidized food grains anywhere in India.",
    fund: "Same PDS entitlements across states",
    tags: ["Food Security", "Migrants"],
  },
  {
    id: 47,
    title: "Solar Charkha Mission",
    emoji: "🧵",
    region: "Central",
    desc: "Promotes solar-powered charkhas to boost rural employment and green energy.",
    fund: "Subsidy + training support",
    tags: ["Renewable Energy", "Rural Employment"],
  },
  {
    id: 48,
    title: "Atal Mission for Rejuvenation and Urban Transformation (AMRUT)",
    emoji: "🏙️",
    region: "Central",
    desc: "Provides basic urban infrastructure like water supply, sewerage, and green spaces.",
    fund: "Project-based funding support",
    tags: ["Urban", "Infrastructure"],
  },
  {
    id: 49,
    title: "National Green Mission",
    emoji: "🌳",
    region: "Central",
    desc: "Mission under NAPCC for afforestation, ecological balance, and carbon sequestration.",
    fund: "Funding for plantation and forest development",
    tags: ["Environment", "Climate Action"],
  },
  {
    id: 50,
    title: "National Digital Health Mission (NDHM)",
    emoji: "📲",
    region: "Central",
    desc: "Creates a digital health ecosystem with health IDs, records, and telemedicine.",
    fund: "Free digital health ID + govt e-health services",
    tags: ["Health", "Digital"],
  },
  {
    id: 51,
    title: "National Electric Mobility Mission (FAME India)",
    emoji: "🚗",
    region: "Central",
    desc: "Promotes adoption of electric and hybrid vehicles through incentives.",
    fund: "Subsidy on EV purchase and charging stations",
    tags: ["Transport", "Environment", "Technology"],
  },
  {
    id: 52,
    title: "National Rural Drinking Water Mission (Jal Jeevan Mission)",
    emoji: "🚰",
    region: "Central",
    desc: "Ensures functional household tap connections to rural households.",
    fund: "100% FHTC coverage with central/state funds",
    tags: ["Water", "Rural Development"],
  },
  {
    id: 53,
    title: "Unnat Bharat Abhiyan",
    emoji: "🌍",
    region: "Central",
    desc: "Links higher educational institutions with villages for sustainable development.",
    fund: "Project-based funding for rural innovations",
    tags: ["Education", "Rural", "Innovation"],
  },
  {
    id: 54,
    title: "Shyama Prasad Mukherji Rurban Mission",
    emoji: "🏘️",
    region: "Central",
    desc: "Develops rural growth clusters with urban amenities while retaining village culture.",
    fund: "Infrastructure + livelihood project support",
    tags: ["Rural", "Infrastructure"],
  },
  {
    id: 55,
    title: "National e-Governance Plan (NeGP)",
    emoji: "🖥️",
    region: "Central",
    desc: "Promotes electronic delivery of government services to improve transparency.",
    fund: "Mission-mode project funding",
    tags: ["Digital", "Governance"],
  },
  {
    id: 56,
    title: "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)",
    emoji: "👨‍🎓",
    region: "Central",
    desc: "Skill development program for rural youth to enhance employability.",
    fund: "Free training + placement support",
    tags: ["Youth", "Skills", "Employment"],
  },
  {
    id: 57,
    title: "National Horticulture Mission",
    emoji: "🍊",
    region: "Central",
    desc: "Promotes holistic growth of horticulture sector including fruits, vegetables, and flowers.",
    fund: "Subsidy + financial support for horticulture",
    tags: ["Agriculture", "Farmers"],
  },
  {
    id: 58,
    title: "Rashtriya Uchchatar Shiksha Abhiyan (RUSA)",
    emoji: "🎒",
    region: "Central",
    desc: "Funds state universities and colleges to improve access, equity, and quality in higher education.",
    fund: "Grant-based institutional funding",
    tags: ["Education", "Higher Education"],
  },
  {
    id: 59,
    title: "PM Atmanirbhar Swasth Bharat Yojana",
    emoji: "⚕️",
    region: "Central",
    desc: "Strengthens health infrastructure and pandemic preparedness across India.",
    fund: "Funding for labs, health centers, and hospitals",
    tags: ["Health", "Infrastructure"],
  },
  {
    id: 60,
    title: "National Youth Policy & Nehru Yuva Kendra Sangathan",
    emoji: "🧑‍🤝‍🧑",
    region: "Central",
    desc: "Engages rural youth in nation-building activities and leadership training.",
    fund: "Youth club support + training grants",
    tags: ["Youth", "Leadership"],
  },
  {
    id: 61,
    title: "PM Street Vendor’s Atmanirbhar Nidhi (PM SVANidhi)",
    emoji: "🛒",
    region: "Central",
    desc: "Micro-credit scheme to support street vendors affected by COVID-19.",
    fund: "Collateral-free loans up to ₹10,000",
    tags: ["Urban", "Employment", "Microfinance"],
  },
  {
    id: 62,
    title: "National Electric Fund for Solar Rooftop (SRISTI)",
    emoji: "🔆",
    region: "Central",
    desc: "Encourages rooftop solar power generation for households and institutions.",
    fund: "Subsidy for solar rooftop installations",
    tags: ["Renewable Energy", "Environment"],
  },
  {
    id: 63,
    title: "Prime Minister’s Employment Generation Programme (PMEGP)",
    emoji: "🏭",
    region: "Central",
    desc: "Credit-linked subsidy scheme for setting up micro-enterprises.",
    fund: "Subsidy up to 35% on project cost",
    tags: ["Entrepreneurship", "MSME"],
  },
  {
    id: 64,
    title: "Pradhan Mantri Krishi Sinchai Yojana (PMKSY)",
    emoji: "💧",
    region: "Central",
    desc: "Aims at improving farm productivity through efficient water use and irrigation.",
    fund: "Irrigation + watershed development funding",
    tags: ["Agriculture", "Farmers"],
  },
  {
    id: 65,
    title: "Solar Pump Distribution (KUSUM Scheme)",
    emoji: "🔋",
    region: "Central",
    desc: "Promotes solar-powered irrigation pumps for farmers to reduce diesel/electricity use.",
    fund: "Up to 60% subsidy on solar pumps",
    tags: ["Farmers", "Renewable Energy"],
  },

  {
    id: 101,
    title: "Khelo India Programme",
    emoji: "🏅",
    region: "Central",
    desc: "National programme to revive sports culture and identify young talent.",
    fund: "Scholarship + training + infrastructure",
    tags: ["Sports", "Youth", "Health"],
  },
  {
    id: 102,
    title: "Mission Indradhanush",
    emoji: "💉",
    region: "Central",
    desc: "Universal immunization programme covering all children and pregnant women.",
    fund: "Free vaccination services",
    tags: ["Health", "Children", "Women"],
  },
  {
    id: 103,
    title: "Kanyashree Prakalpa (West Bengal)",
    emoji: "👧",
    region: "State",
    desc: "Cash transfers to adolescent girls to promote education and delay marriage.",
    fund: "₹750 – ₹25,000 depending on stage",
    tags: ["Girls", "Education", "Welfare"],
  },
  {
    id: 104,
    title: "Rythu Bandhu Scheme (Telangana)",
    emoji: "🌱",
    region: "State",
    desc: "Investment support for farmers for each crop season.",
    fund: "₹5,000 per acre per season",
    tags: ["Farmers", "Agriculture"],
  },
  {
    id: 105,
    title: "Mukhyamantri Chiranjeevi Swasthya Bima Yojana (Rajasthan)",
    emoji: "🩺",
    region: "State",
    desc: "Cashless health insurance for state residents.",
    fund: "₹25 lakh per family per year",
    tags: ["Health", "Insurance"],
  },
  {
    id: 106,
    title: "Kudumbashree Mission (Kerala)",
    emoji: "👩‍👩‍👧",
    region: "State",
    desc: "Women empowerment and poverty eradication through SHGs.",
    fund: "Revolving fund + livelihood support",
    tags: ["Women", "Self Help Groups"],
  },
  {
    id: 107,
    title: "Rajiv Gandhi Kisan Nyay Yojana (Chhattisgarh)",
    emoji: "🌾",
    region: "State",
    desc: "Direct income support to farmers for crop cultivation.",
    fund: "₹9,000 – ₹10,000 per acre annually",
    tags: ["Farmers", "Income Support"],
  },
  {
    id: 108,
    title: "Amma Canteen (Tamil Nadu)",
    emoji: "🍛",
    region: "State",
    desc: "Low-cost nutritious meals for urban poor.",
    fund: "₹1 – ₹5 per meal subsidy",
    tags: ["Food Security", "Urban"],
  },
  {
    id: 109,
    title: "Saur Sujala Yojana (Chhattisgarh)",
    emoji: "☀️",
    region: "State",
    desc: "Provides solar pumps to farmers for irrigation.",
    fund: "70–90% subsidy on solar pumps",
    tags: ["Farmers", "Energy", "Renewable"],
  },
  {
    id: 110,
    title: "Mission Bhagiratha (Telangana)",
    emoji: "🚰",
    region: "State",
    desc: "Safe drinking water supply to rural households.",
    fund: "Infrastructure + pipeline support",
    tags: ["Water", "Rural Development"],
  },
  {
    id: 111,
    title: "Mukhya Mantri Yuva Nestham (Andhra Pradesh)",
    emoji: "🧑‍💼",
    region: "State",
    desc: "Unemployment allowance for educated youth.",
    fund: "₹1,000 – ₹1,500 per month",
    tags: ["Youth", "Employment"],
  },
  {
    id: 112,
    title: "Sabooj Sathi (West Bengal)",
    emoji: "🚲",
    region: "State",
    desc: "Free bicycles to school-going students.",
    fund: "Free distribution",
    tags: ["Education", "Transport", "Students"],
  },
  {
    id: 113,
    title: "Sandhya Suraksha Yojana (Karnataka)",
    emoji: "👴",
    region: "State",
    desc: "Monthly pension for destitute senior citizens.",
    fund: "₹1,000 – ₹1,500 per month",
    tags: ["Senior Citizens", "Pension"],
  },
  {
    id: 114,
    title: "Mukhyamantri Shiksha Puraskar Yojana (Odisha)",
    emoji: "🏆",
    region: "State",
    desc: "Rewards and incentives to schools and students for excellence.",
    fund: "Cash awards up to ₹1 lakh",
    tags: ["Education", "Students"],
  },
  {
    id: 115,
    title: "Samagra Shiksha Abhiyan",
    emoji: "🎒",
    region: "Central",
    desc: "Holistic school education from pre-primary to senior secondary.",
    fund: "School grants + teacher training support",
    tags: ["Education", "Schools"],
  },
  {
    id: 116,
    title: "Krishi Bhagya Yojana (Karnataka)",
    emoji: "🚜",
    region: "State",
    desc: "Promotes water conservation and sustainable farming.",
    fund: "Subsidy for farm ponds and equipment",
    tags: ["Farmers", "Water", "Sustainability"],
  },
  {
    id: 117,
    title: "PM Surakshit Matritva Abhiyan",
    emoji: "🤰",
    region: "Central",
    desc: "Free health check-ups for pregnant women on the 9th of every month.",
    fund: "Free diagnostics + treatment",
    tags: ["Health", "Women"],
  },
  {
    id: 118,
    title: "Rajiv Aarogyasri (Andhra Pradesh & Telangana)",
    emoji: "🧑‍⚕️",
    region: "State",
    desc: "Cashless medical treatment for BPL families.",
    fund: "₹5 lakh per family/year",
    tags: ["Health", "Insurance"],
  },
  {
    id: 119,
    title: "Delhi Ladli Scheme",
    emoji: "👶",
    region: "State",
    desc: "Financial assistance to girl children for education and marriage.",
    fund: "₹11,000 – ₹1 lakh in installments",
    tags: ["Girls", "Education", "Welfare"],
  },
  {
    id: 120,
    title: "PM Kisan Sampada Yojana",
    emoji: "🥫",
    region: "Central",
    desc: "Boosts agro-processing and value addition in the food sector.",
    fund: "Grants up to ₹5 crore for projects",
    tags: ["Agriculture", "Food Processing"],
  },
  {
    id: 121,
    title: "Mukhyamantri Kanya Vivah Yojana (Madhya Pradesh)",
    emoji: "💍",
    region: "State",
    desc: "Financial aid for marriage of daughters from poor families.",
    fund: "₹51,000 assistance per marriage",
    tags: ["Women", "Marriage", "Welfare"],
  },
  {
    id: 122,
    title: "YSR Rythu Bharosa (Andhra Pradesh)",
    emoji: "🌿",
    region: "State",
    desc: "Income support to farmers for crop investment.",
    fund: "₹13,500 per year to farmers",
    tags: ["Farmers", "Agriculture", "Support"],
  },
  {
    id: 123,
    title: "Sukanya Samriddhi Yojana",
    emoji: "👧",
    region: "Central",
    desc: "Savings scheme for girl child’s education and marriage expenses.",
    fund: "Up to ₹1.5 lakh yearly deposit with high interest",
    tags: ["Girls", "Savings", "Education"],
  },
  {
    id: 124,
    title: "Mukhyamantri Krishi Ashirwad Yojana (Jharkhand)",
    emoji: "🌾",
    region: "State",
    desc: "Financial support to small and marginal farmers.",
    fund: "₹5,000 per acre annually",
    tags: ["Farmers", "Agriculture"],
  },
  {
    id: 125,
    title: "YSR Cheyutha (Andhra Pradesh)",
    emoji: "👩‍🦳",
    region: "State",
    desc: "Support to women from SC, ST, OBC, and minority groups aged 45–60.",
    fund: "₹75,000 over 4 years",
    tags: ["Women", "Livelihood"],
  },
  {
    id: 126,
    title: "Mukhyamantri Amrutum Yojana (Gujarat)",
    emoji: "🧑‍⚕️",
    region: "State",
    desc: "Health insurance scheme for BPL and lower-income groups.",
    fund: "₹5 lakh per family/year",
    tags: ["Health", "Insurance"],
  },
  {
    id: 127,
    title: "Madhubabu Pension Yojana (Odisha)",
    emoji: "🧓",
    region: "State",
    desc: "Monthly pension for elderly, widows, and disabled persons.",
    fund: "₹500 – ₹1,200/month",
    tags: ["Pension", "Senior Citizens", "Disability"],
  },
  {
    id: 128,
    title: "Samajik Suraksha Pension Yojana (Haryana)",
    emoji: "🏦",
    region: "State",
    desc: "Pension scheme for elderly, widows, and disabled residents.",
    fund: "₹2,750 per month",
    tags: ["Pension", "Welfare"],
  },
  {
    id: 129,
    title: "Mukhyamantri Balika Cycle Yojana (Bihar)",
    emoji: "🚴‍♀️",
    region: "State",
    desc: "Free cycles for girl students to promote education and reduce dropouts.",
    fund: "Cycle worth ₹3,000 provided",
    tags: ["Girls", "Education", "Transport"],
  },
  {
    id: 130,
    title: "YSR Aasara (Andhra Pradesh)",
    emoji: "👭",
    region: "State",
    desc: "Financial support to women SHGs by reimbursing outstanding bank loans.",
    fund: "₹25,000 – ₹1 lakh loan waiver",
    tags: ["Women", "Self Help Groups"],
  },
  {
    id: 131,
    title: "Ekalavya Model Residential Schools",
    emoji: "🏫",
    region: "Central",
    desc: "Residential schools for ST students to ensure quality education.",
    fund: "Free boarding, education, and facilities",
    tags: ["Education", "Tribal"],
  },
  {
    id: 132,
    title: "Bhagyalakshmi Scheme (Karnataka)",
    emoji: "👶",
    region: "State",
    desc: "Encourages birth of girl child by financial support to families.",
    fund: "₹1 lakh maturity benefit on girl turning 18",
    tags: ["Girls", "Savings", "Welfare"],
  },
  {
    id: 133,
    title: "Mukhyamantri Chhatra Yojana (Bihar)",
    emoji: "📖",
    region: "State",
    desc: "Financial support for higher education of SC/ST/OBC students.",
    fund: "₹10,000 – ₹50,000 depending on course",
    tags: ["Education", "Students"],
  },
  {
    id: 134,
    title: "Rajiv Gandhi Rural Housing Corporation (Karnataka)",
    emoji: "🏘️",
    region: "State",
    desc: "Housing scheme for economically weaker sections in rural areas.",
    fund: "Subsidized pucca houses",
    tags: ["Housing", "Rural"],
  },
  {
    id: 135,
    title: "Mahatma Gandhi Bunkar Bima Yojana",
    emoji: "🧵",
    region: "Central",
    desc: "Insurance scheme for handloom weavers.",
    fund: "Life insurance up to ₹60,000",
    tags: ["Weavers", "Insurance"],
  },
  {
    id: 136,
    title: "Delhi Annashree Yojana",
    emoji: "🥗",
    region: "State",
    desc: "Direct cash transfer for food security to poor households.",
    fund: "₹600 per month per family",
    tags: ["Food Security", "Urban"],
  },
  {
    id: 137,
    title: "Mukhyamantri Old Age Samman Allowance (Delhi)",
    emoji: "🧓",
    region: "State",
    desc: "Pension support to elderly residents of Delhi.",
    fund: "₹2,000 – ₹2,500/month",
    tags: ["Senior Citizens", "Pension"],
  },
  {
    id: 138,
    title: "Solar Rooftop Subsidy Scheme",
    emoji: "🌞",
    region: "Central",
    desc: "Encourages adoption of rooftop solar panels by households.",
    fund: "40% subsidy for up to 3kW systems",
    tags: ["Energy", "Environment"],
  },
  {
    id: 139,
    title: "Jagananna Amma Vodi (Andhra Pradesh)",
    emoji: "📚",
    region: "State",
    desc: "Financial support to mothers for children’s school education.",
    fund: "₹15,000 per child/year",
    tags: ["Education", "Women", "Children"],
  },
  {
    id: 140,
    title: "Rajiv Gandhi Shramik Kalyan Yojana",
    emoji: "👨‍🏭",
    region: "Central",
    desc: "Unemployment allowance for industrial workers who lose jobs.",
    fund: "50% – 60% of wages for up to 1 year",
    tags: ["Workers", "Unemployment"],
  },

  {
    id: 141,
    title: "Assistance to Disabled Persons for Purchase/Fitting of Aids & Appliances (ADIP)",
    emoji: "🦾",
    region: "Central",
    desc: "Provides assistive devices like wheelchairs, hearing aids, and prosthetics to eligible PwDs.",
    fund: "100% cost if income ≤ ₹22,500/month; 50% if ₹22,501–₹30,000. Motorized tricycle/wheelchair subsidy up to ₹50,000.",
    tags: ["Assistive Devices", "Inclusion", "Direct Aid"],
  },
  {
    id: 142,
    title: "Niramaya Health Insurance Scheme",
    emoji: "🩺",
    region: "Central",
    desc: "Affordable health insurance for PwDs covering OPD, hospitalization, therapies, and corrective surgery.",
    fund: "Coverage up to ₹1 lakh/year. Premium: ₹250/year (BPL), ₹500/year (others).",
    tags: ["Health", "Insurance", "Direct Aid"],
  },
  {
    id: 143,
    title: "Scholarships for Students with Disabilities",
    emoji: "📝",
    region: "Central",
    desc: "Scholarships for school and college students with disabilities to support education.",
    fund: "Pre-matric: ₹350–₹600/month + ₹1,000–₹1,500/year. Post-matric: ₹230–₹550/month + ₹1,600–₹1,750/year.",
    tags: ["Education", "Scholarship", "Direct Aid"],
  },
  {
    id: 144,
    title: "National Fellowship for Persons with Disabilities",
    emoji: "🎓",
    region: "Central",
    desc: "Fellowship for M.Phil/Ph.D students with benchmark disabilities.",
    fund: "JRF: ₹31,000/month (first 2 years); SRF: ₹35,000/month (next 3 years) + Contingency ₹10,000–₹25,000/year + Escort ₹2,000/month + HRA.",
    tags: ["Higher Education", "Research", "Direct Aid"],
  },
  {
    id: 145,
    title: "National Handicapped Finance & Development Corporation (NHFDC/NDFDC) Loans",
    emoji: "💰",
    region: "Central",
    desc: "Provides concessional loans to PwDs for self-employment, education, and skill development.",
    fund: "Up to ₹25 lakh for self-employment @ 5–9% interest; up to ₹10 lakh for education loans.",
    tags: ["Finance", "Employment", "Direct Aid"],
  },
  {
    id: 146,
    title: "Skill Development Programme for PwDs",
    emoji: "🛠",
    region: "Central",
    desc: "Special skill and entrepreneurship training for persons with disabilities.",
    fund: "Free training + stipend ₹1,000–₹1,500/month + free boarding & lodging.",
    tags: ["Skills", "Employment", "Direct Aid"],
  },
  {
    id: 147,
    title: "Incentive Scheme for Employers of PwDs",
    emoji: "🏢",
    region: "Central",
    desc: "Encourages companies to hire PwDs by reimbursing EPF and ESI contributions.",
    fund: "100% of employer EPF (12%) + ESI (3.25%) contribution covered for first 3 years.",
    tags: ["Employment", "Inclusion", "Direct Aid"],
  },
  {
    id: 148,
    title: "State Disability Pension Schemes",
    emoji: "🧑‍🦽",
    region: "State",
    desc: "Monthly pension to eligible PwDs under state government social welfare programs.",
    fund: "₹1,000 – ₹3,000 per month (varies by state, e.g., Tamil Nadu ₹1,500, Delhi ₹2,500).",
    tags: ["Pension", "Social Security", "Direct Aid"],
  },
  {
    id: 149,
    title: "Indira Gandhi National Disability Pension Scheme (IGNDPS)",
    emoji: "👵",
    region: "Central + State",
    desc: "Social assistance for persons with severe or multiple disabilities, especially from BPL households.",
    fund: "₹300/month from Central Govt + State top-up (many states add ₹700–₹2,000).",
    tags: ["Pension", "Social Security", "Direct Aid"],
  },
];

export default SCHEMES;
